"""Add Go-Live import pipeline fields to Booking and ImportLog models

Revision ID: c4938c47a2f2
Revises: e52c863e9aca
Create Date: 2025-10-08 11:41:22.919501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4938c47a2f2'
down_revision: Union[str, Sequence[str], None] = 'e52c863e9aca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('importlog')
    op.drop_index(op.f('ix_expense_allocations_allocated_amount'), table_name='expense_allocations')
    op.drop_index(op.f('ix_expense_allocations_expense_id'), table_name='expense_allocations')
    op.drop_index(op.f('ix_expense_allocations_month'), table_name='expense_allocations')
    op.drop_index(op.f('ix_expense_allocations_property_id'), table_name='expense_allocations')
    op.drop_table('expense_allocations')
    op.drop_index(op.f('ix_building_building_name'), table_name='building')
    op.drop_table('building')
    op.drop_index(op.f('ix_expenses_allocation_method'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_amount'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_building_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_category_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_created_at'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_date'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_month'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_property_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_vendor'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_room_assignments_booking_id'), table_name='room_assignments')
    op.drop_table('room_assignments')
    op.drop_index(op.f('ix_recurring_expenses_amount'), table_name='recurring_expenses')
    op.drop_index(op.f('ix_recurring_expenses_building_id'), table_name='recurring_expenses')
    op.drop_index(op.f('ix_recurring_expenses_category_id'), table_name='recurring_expenses')
    op.drop_index(op.f('ix_recurring_expenses_day_of_month'), table_name='recurring_expenses')
    op.drop_index(op.f('ix_recurring_expenses_end_month'), table_name='recurring_expenses')
    op.drop_index(op.f('ix_recurring_expenses_is_active'), table_name='recurring_expenses')
    op.drop_index(op.f('ix_recurring_expenses_property_id'), table_name='recurring_expenses')
    op.drop_index(op.f('ix_recurring_expenses_start_month'), table_name='recurring_expenses')
    op.drop_index(op.f('ix_recurring_expenses_vendor'), table_name='recurring_expenses')
    op.drop_table('recurring_expenses')
    op.drop_table('extra_charges')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_handovers_id'), table_name='handovers')
    op.drop_table('handovers')
    op.drop_index(op.f('idx_expense_cat_hierarchy'), table_name='expense_categories')
    op.drop_index(op.f('ix_expense_categories_is_fixed'), table_name='expense_categories')
    op.drop_index(op.f('ix_expense_categories_name'), table_name='expense_categories')
    op.drop_index(op.f('ix_expense_categories_parent_id'), table_name='expense_categories')
    op.drop_table('expense_categories')
    op.drop_index(op.f('ix_user_created_at'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_is_active'), table_name='user')
    op.drop_index(op.f('ix_user_last_login'), table_name='user')
    op.drop_index(op.f('ix_user_role'), table_name='user')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_usersession_created_at'), table_name='usersession')
    op.drop_index(op.f('ix_usersession_expires_at'), table_name='usersession')
    op.drop_index(op.f('ix_usersession_is_active'), table_name='usersession')
    op.drop_index(op.f('ix_usersession_user_id'), table_name='usersession')
    op.drop_table('usersession')
    op.drop_index(op.f('ix_booking_booking_date'), table_name='booking')
    op.drop_index(op.f('ix_booking_channel_id'), table_name='booking')
    op.drop_index(op.f('ix_booking_confirmation_code'), table_name='booking')
    op.drop_index(op.f('ix_booking_created_at'), table_name='booking')
    op.drop_index(op.f('ix_booking_end_date'), table_name='booking')
    op.drop_index(op.f('ix_booking_property_id'), table_name='booking')
    op.drop_index(op.f('ix_booking_start_date'), table_name='booking')
    op.drop_index(op.f('ix_booking_status'), table_name='booking')
    op.drop_index(op.f('ix_booking_total_payout_vnd'), table_name='booking')
    op.drop_table('booking')
    op.drop_index(op.f('ix_channel_channel_name'), table_name='channel')
    op.drop_index(op.f('ix_channel_is_active'), table_name='channel')
    op.drop_table('channel')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_salesperson_email'), table_name='salesperson')
    op.drop_index(op.f('ix_salesperson_name'), table_name='salesperson')
    op.drop_table('salesperson')
    op.drop_index(op.f('ix_import_log_filename'), table_name='import_log')
    op.drop_index(op.f('ix_import_log_imported_at'), table_name='import_log')
    op.drop_index(op.f('ix_import_log_rows_processed'), table_name='import_log')
    op.drop_index(op.f('ix_import_log_user_id'), table_name='import_log')
    op.drop_table('import_log')
    op.drop_index(op.f('ix_property_building_id'), table_name='property')
    op.drop_index(op.f('ix_property_is_active'), table_name='property')
    op.drop_index(op.f('ix_property_price_per_night'), table_name='property')
    op.drop_index(op.f('ix_property_room_number'), table_name='property')
    op.drop_index(op.f('ix_property_room_type'), table_name='property')
    op.drop_table('property')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('building_id', sa.INTEGER(), nullable=True),
    sa.Column('building_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('room_number', sa.VARCHAR(length=20), nullable=True),
    sa.Column('room_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('area_sqm', sa.FLOAT(), nullable=True),
    sa.Column('price_per_night', sa.INTEGER(), nullable=True),
    sa.Column('max_guests', sa.INTEGER(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('building_code', sa.VARCHAR(), nullable=True),
    sa.Column('property_name', sa.VARCHAR(), nullable=False),
    sa.Column('airbnb_name', sa.VARCHAR(), nullable=True),
    sa.Column('unit_number', sa.VARCHAR(), nullable=True),
    sa.Column('unit_short', sa.VARCHAR(), nullable=True),
    sa.Column('property_short', sa.VARCHAR(), nullable=True),
    sa.Column('address', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('base_price', sa.FLOAT(), nullable=True),
    sa.Column('latitude', sa.FLOAT(), nullable=True),
    sa.Column('longitude', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['building.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_room_type'), 'property', ['room_type'], unique=False)
    op.create_index(op.f('ix_property_room_number'), 'property', ['room_number'], unique=False)
    op.create_index(op.f('ix_property_price_per_night'), 'property', ['price_per_night'], unique=False)
    op.create_index(op.f('ix_property_is_active'), 'property', ['is_active'], unique=False)
    op.create_index(op.f('ix_property_building_id'), 'property', ['building_id'], unique=False)
    op.create_table('import_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), nullable=False),
    sa.Column('imported_at', sa.DATETIME(), nullable=False),
    sa.Column('rows_processed', sa.INTEGER(), nullable=False),
    sa.Column('rows_successful', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_log_user_id'), 'import_log', ['user_id'], unique=False)
    op.create_index(op.f('ix_import_log_rows_processed'), 'import_log', ['rows_processed'], unique=False)
    op.create_index(op.f('ix_import_log_imported_at'), 'import_log', ['imported_at'], unique=False)
    op.create_index(op.f('ix_import_log_filename'), 'import_log', ['filename'], unique=False)
    op.create_table('salesperson',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('commission_rate', sa.FLOAT(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('phone', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salesperson_name'), 'salesperson', ['name'], unique=False)
    op.create_index(op.f('ix_salesperson_email'), 'salesperson', ['email'], unique=1)
    op.create_table('payments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('booking_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('guest_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('amount_due', sa.FLOAT(), nullable=False),
    sa.Column('amount_collected', sa.FLOAT(), nullable=False),
    sa.Column('payment_method', sa.VARCHAR(length=30), nullable=False),
    sa.Column('collected_by', sa.VARCHAR(length=50), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('receipt_image', sa.VARCHAR(length=255), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('added_by_user_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_table('channel',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('channel_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('commission_rate', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_is_active'), 'channel', ['is_active'], unique=False)
    op.create_index(op.f('ix_channel_channel_name'), 'channel', ['channel_name'], unique=1)
    op.create_table('booking',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('confirmation_code', sa.VARCHAR(length=50), nullable=True),
    sa.Column('property_id', sa.INTEGER(), nullable=True),
    sa.Column('channel_id', sa.INTEGER(), nullable=True),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.Column('booking_date', sa.DATE(), nullable=True),
    sa.Column('num_nights', sa.INTEGER(), nullable=True),
    sa.Column('num_adults', sa.INTEGER(), nullable=True),
    sa.Column('num_children', sa.INTEGER(), nullable=True),
    sa.Column('num_infants', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('total_payout_vnd', sa.INTEGER(), nullable=True),
    sa.Column('guest_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('guest_contact', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('listing_raw', sa.VARCHAR(), nullable=True),
    sa.Column('salesperson_id', sa.INTEGER(), nullable=True),
    sa.Column('notes', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.ForeignKeyConstraint(['salesperson_id'], ['salesperson.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_total_payout_vnd'), 'booking', ['total_payout_vnd'], unique=False)
    op.create_index(op.f('ix_booking_status'), 'booking', ['status'], unique=False)
    op.create_index(op.f('ix_booking_start_date'), 'booking', ['start_date'], unique=False)
    op.create_index(op.f('ix_booking_property_id'), 'booking', ['property_id'], unique=False)
    op.create_index(op.f('ix_booking_end_date'), 'booking', ['end_date'], unique=False)
    op.create_index(op.f('ix_booking_created_at'), 'booking', ['created_at'], unique=False)
    op.create_index(op.f('ix_booking_confirmation_code'), 'booking', ['confirmation_code'], unique=1)
    op.create_index(op.f('ix_booking_channel_id'), 'booking', ['channel_id'], unique=False)
    op.create_index(op.f('ix_booking_booking_date'), 'booking', ['booking_date'], unique=False)
    op.create_table('usersession',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('token_jti', sa.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=45), nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_jti')
    )
    op.create_index(op.f('ix_usersession_user_id'), 'usersession', ['user_id'], unique=False)
    op.create_index(op.f('ix_usersession_is_active'), 'usersession', ['is_active'], unique=False)
    op.create_index(op.f('ix_usersession_expires_at'), 'usersession', ['expires_at'], unique=False)
    op.create_index(op.f('ix_usersession_created_at'), 'usersession', ['created_at'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=255), nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('is_verified', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.Column('accessible_properties', sa.VARCHAR(), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=1)
    op.create_index(op.f('ix_user_role'), 'user', ['role'], unique=False)
    op.create_index(op.f('ix_user_last_login'), 'user', ['last_login'], unique=False)
    op.create_index(op.f('ix_user_is_active'), 'user', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=1)
    op.create_index(op.f('ix_user_created_at'), 'user', ['created_at'], unique=False)
    op.create_table('expense_categories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('parent_id', sa.INTEGER(), nullable=True),
    sa.Column('is_fixed', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['expense_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_categories_parent_id'), 'expense_categories', ['parent_id'], unique=False)
    op.create_index(op.f('ix_expense_categories_name'), 'expense_categories', ['name'], unique=False)
    op.create_index(op.f('ix_expense_categories_is_fixed'), 'expense_categories', ['is_fixed'], unique=False)
    op.create_index(op.f('idx_expense_cat_hierarchy'), 'expense_categories', ['parent_id', 'name'], unique=False)
    op.create_table('handovers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('handover_by_user_id', sa.INTEGER(), nullable=False),
    sa.Column('recipient_user_id', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('handover_image', sa.VARCHAR(length=255), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('signature_status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_handovers_id'), 'handovers', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=15), nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=1)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('extra_charges',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('property_id', sa.INTEGER(), nullable=False),
    sa.Column('charge_name', sa.VARCHAR(), nullable=False),
    sa.Column('charge_amount', sa.INTEGER(), nullable=False),
    sa.Column('charge_month', sa.VARCHAR(), nullable=False),
    sa.Column('charge_note', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.VARCHAR(), nullable=True),
    sa.Column('category_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recurring_expenses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('category_id', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.INTEGER(), nullable=False),
    sa.Column('vendor', sa.VARCHAR(length=255), nullable=True),
    sa.Column('note', sa.VARCHAR(length=500), nullable=True),
    sa.Column('building_id', sa.INTEGER(), nullable=True),
    sa.Column('property_id', sa.INTEGER(), nullable=True),
    sa.Column('allocation_method', sa.VARCHAR(length=50), nullable=False),
    sa.Column('start_month', sa.VARCHAR(), nullable=False),
    sa.Column('end_month', sa.VARCHAR(), nullable=True),
    sa.Column('day_of_month', sa.INTEGER(), nullable=False),
    sa.Column('is_active', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['expense_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurring_expenses_vendor'), 'recurring_expenses', ['vendor'], unique=False)
    op.create_index(op.f('ix_recurring_expenses_start_month'), 'recurring_expenses', ['start_month'], unique=False)
    op.create_index(op.f('ix_recurring_expenses_property_id'), 'recurring_expenses', ['property_id'], unique=False)
    op.create_index(op.f('ix_recurring_expenses_is_active'), 'recurring_expenses', ['is_active'], unique=False)
    op.create_index(op.f('ix_recurring_expenses_end_month'), 'recurring_expenses', ['end_month'], unique=False)
    op.create_index(op.f('ix_recurring_expenses_day_of_month'), 'recurring_expenses', ['day_of_month'], unique=False)
    op.create_index(op.f('ix_recurring_expenses_category_id'), 'recurring_expenses', ['category_id'], unique=False)
    op.create_index(op.f('ix_recurring_expenses_building_id'), 'recurring_expenses', ['building_id'], unique=False)
    op.create_index(op.f('ix_recurring_expenses_amount'), 'recurring_expenses', ['amount'], unique=False)
    op.create_table('room_assignments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('booking_id', sa.INTEGER(), nullable=False),
    sa.Column('booked_room', sa.VARCHAR(), nullable=True),
    sa.Column('actual_room', sa.VARCHAR(), nullable=True),
    sa.Column('revenue_attribution', sa.VARCHAR(), nullable=False),
    sa.Column('change_reason', sa.VARCHAR(), nullable=True),
    sa.Column('changed_date', sa.DATE(), nullable=True),
    sa.Column('changed_by', sa.VARCHAR(), nullable=True),
    sa.Column('notes', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_assignments_booking_id'), 'room_assignments', ['booking_id'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.VARCHAR(), nullable=False),
    sa.Column('month', sa.VARCHAR(), nullable=True),
    sa.Column('category_id', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.INTEGER(), nullable=False),
    sa.Column('vendor', sa.VARCHAR(length=255), nullable=True),
    sa.Column('note', sa.VARCHAR(length=500), nullable=True),
    sa.Column('building_id', sa.INTEGER(), nullable=True),
    sa.Column('property_id', sa.INTEGER(), nullable=True),
    sa.Column('allocation_method', sa.VARCHAR(length=50), nullable=False),
    sa.Column('allocation_basis_note', sa.VARCHAR(length=500), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['expense_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_vendor'), 'expenses', ['vendor'], unique=False)
    op.create_index(op.f('ix_expenses_property_id'), 'expenses', ['property_id'], unique=False)
    op.create_index(op.f('ix_expenses_month'), 'expenses', ['month'], unique=False)
    op.create_index(op.f('ix_expenses_date'), 'expenses', ['date'], unique=False)
    op.create_index(op.f('ix_expenses_created_at'), 'expenses', ['created_at'], unique=False)
    op.create_index(op.f('ix_expenses_category_id'), 'expenses', ['category_id'], unique=False)
    op.create_index(op.f('ix_expenses_building_id'), 'expenses', ['building_id'], unique=False)
    op.create_index(op.f('ix_expenses_amount'), 'expenses', ['amount'], unique=False)
    op.create_index(op.f('ix_expenses_allocation_method'), 'expenses', ['allocation_method'], unique=False)
    op.create_table('building',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('building_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('building_code', sa.VARCHAR(length=50), nullable=True),
    sa.Column('address', sa.VARCHAR(length=500), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('latitude', sa.FLOAT(), nullable=True),
    sa.Column('longitude', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building_code')
    )
    op.create_index(op.f('ix_building_building_name'), 'building', ['building_name'], unique=False)
    op.create_table('expense_allocations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('expense_id', sa.INTEGER(), nullable=False),
    sa.Column('property_id', sa.INTEGER(), nullable=False),
    sa.Column('month', sa.VARCHAR(), nullable=False),
    sa.Column('allocated_amount', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_allocations_property_id'), 'expense_allocations', ['property_id'], unique=False)
    op.create_index(op.f('ix_expense_allocations_month'), 'expense_allocations', ['month'], unique=False)
    op.create_index(op.f('ix_expense_allocations_expense_id'), 'expense_allocations', ['expense_id'], unique=False)
    op.create_index(op.f('ix_expense_allocations_allocated_amount'), 'expense_allocations', ['allocated_amount'], unique=False)
    op.create_table('importlog',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.VARCHAR(), nullable=False),
    sa.Column('source', sa.VARCHAR(), nullable=False),
    sa.Column('rows_inserted', sa.INTEGER(), nullable=False),
    sa.Column('rows_updated', sa.INTEGER(), nullable=False),
    sa.Column('started_at', sa.DATETIME(), nullable=False),
    sa.Column('finished_at', sa.DATETIME(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('message', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
