"""Create expense_categories table and fix foreign key

Revision ID: e52c863e9aca
Revises: ff2cc8a4dc60
Create Date: 2025-10-04 20:54:18.100880

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e52c863e9aca"
down_revision: Union[str, Sequence[str], None] = "ff2cc8a4dc60"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create expense_categories table
    op.create_table(
        "expense_categories",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), nullable=False),
        sa.Column("parent_id", sa.INTEGER(), nullable=True),
        sa.Column("is_fixed", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["expense_categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_expense_cat_hierarchy",
        "expense_categories",
        ["parent_id", "name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_expense_categories_is_fixed"),
        "expense_categories",
        ["is_fixed"],
        unique=False,
    )
    op.create_index(
        op.f("ix_expense_categories_name"), "expense_categories", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_expense_categories_parent_id"),
        "expense_categories",
        ["parent_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop expense_categories table
    op.drop_index(
        op.f("ix_expense_categories_parent_id"), table_name="expense_categories"
    )
    op.drop_index(op.f("ix_expense_categories_name"), table_name="expense_categories")
    op.drop_index(
        op.f("ix_expense_categories_is_fixed"), table_name="expense_categories"
    )
    op.drop_index("idx_expense_cat_hierarchy", table_name="expense_categories")
    op.drop_table("expense_categories")
    # ### end Alembic commands ###
