#!/bin/bash
# 🚀 CREATE BRAIN FROM TEMPLATE - Bash Script  
# Mục tiêu: Setup brain system từ template trong < 5 phút

# Colors cho output
RED='\033[0;31m'
GREEN='\033[0;32m' 
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

success() { echo -e "${GREEN}✅ $1${NC}"; }
warning() { echo -e "${YELLOW}⚠️ $1${NC}"; }
error() { echo -e "${RED}❌ $1${NC}"; }
info() { echo -e "${CYAN}ℹ️ $1${NC}"; }

# Parse arguments
PROJECT_NAME=""
TEAM="Development Team"
DOMAIN="SaaS"
TARGET_PATH=".brain"

while [[ $# -gt 0 ]]; do
    case $1 in
        --project-name)
            PROJECT_NAME="$2"
            shift 2
            ;;
        --team)
            TEAM="$2"
            shift 2
            ;;
        --domain)
            DOMAIN="$2"
            shift 2
            ;;
        --target-path)
            TARGET_PATH="$2"
            shift 2
            ;;
        *)
            error "Unknown parameter: $1"
            echo "Usage: $0 --project-name NAME [--team TEAM] [--domain DOMAIN] [--target-path PATH]"
            exit 1
            ;;
    esac
done

if [ -z "$PROJECT_NAME" ]; then
    error "Project name is required!"
    echo "Usage: $0 --project-name NAME [--team TEAM] [--domain DOMAIN]"
    exit 1
fi

info "🚀 BẮT ĐẦU SETUP BRAIN SYSTEM CHO DỰ ÁN: $PROJECT_NAME"
START_TIME=$(date +%s)
info "⏱️ Thời gian bắt đầu: $(date)"

# Kiểm tra PROJECT_TEMPLATE
TEMPLATE_PATH=".brain/PROJECT_TEMPLATE"
if [ ! -d "$TEMPLATE_PATH" ]; then
    error "Không tìm thấy thư mục $TEMPLATE_PATH"
    info "Hãy đảm bảo bạn đang chạy script từ root directory của dự án"
    exit 1
fi

success "Tìm thấy template directory: $TEMPLATE_PATH"

# Tạo thư mục đích
mkdir -p "$TARGET_PATH/tasks" "$TARGET_PATH/context" "$TARGET_PATH/logs/daily"
success "Đã tạo cấu trúc thư mục brain system"

# Copy và rename template files
declare -A TEMPLATE_FILES=(
    ["TEMPLATE_SCOPE.md"]="SCOPE.md"
    ["TEMPLATE_DOMAIN_MAP.md"]="DOMAIN_MAP.md"
    ["SAMPLE_ACTIVE_TASKS.json"]="tasks/ACTIVE_TASKS.json"
    ["QUICK_START.md"]="QUICK_START.md"
    ["SETUP_GUIDE.md"]="SETUP_GUIDE.md"
    ["INDEX.md"]="README.md"
)

info "📁 Đang copy và rename template files..."
COPIED_FILES=()

for source_file in "${!TEMPLATE_FILES[@]}"; do
    dest_file="${TEMPLATE_FILES[$source_file]}"
    source_path="$TEMPLATE_PATH/$source_file"
    dest_path="$TARGET_PATH/$dest_file"
    
    if [ -f "$source_path" ]; then
        cp "$source_path" "$dest_path"
        COPIED_FILES+=("$dest_path")
        success "Copied: $source_file → $dest_file"
    else
        warning "Không tìm thấy: $source_file"
    fi
done

# Thay thế placeholders
CURRENT_DATE=$(date +%Y-%m-%d)
CURRENT_DATETIME=$(date +"%Y-%m-%d %H:%M")

declare -A PLACEHOLDERS=(
    ["{{PROJECT_NAME}}"]="$PROJECT_NAME"
    ["{{TEAM_NAME}}"]="$TEAM"
    ["{{DOMAIN}}"]="$DOMAIN"
    ["{{CURRENT_DATE}}"]="$CURRENT_DATE"
    ["{{LAST_UPDATED}}"]="$CURRENT_DATE"
    ["{{LAST_UPDATE_DATE}}"]="$CURRENT_DATETIME"
    ["{{VERSION}}"]="1.0.0"
    ["{{STATUS}}"]="Development"
    ["{{CREATION_DATE}}"]="$CURRENT_DATE"
)

info "🔄 Đang thay thế placeholders trong các file..."
REPLACED_COUNT=0

for file_path in "${COPIED_FILES[@]}"; do
    if [ -f "$file_path" ]; then
        temp_file=$(mktemp)
        cp "$file_path" "$temp_file"
        
        for placeholder in "${!PLACEHOLDERS[@]}"; do
            replacement="${PLACEHOLDERS[$placeholder]}"
            sed -i.bak "s|${placeholder}|${replacement}|g" "$file_path"
        done
        
        # Check if file was modified
        if ! diff -q "$temp_file" "$file_path" > /dev/null 2>&1; then
            ((REPLACED_COUNT++))
            success "Updated placeholders in: $(basename "$file_path")"
        fi
        
        rm "$temp_file" "$file_path.bak" 2>/dev/null
    fi
done

# Tạo CONTEXT_INDEX.md
CONTEXT_INDEX_PATH="$TARGET_PATH/context/CONTEXT_INDEX.md"
cat > "$CONTEXT_INDEX_PATH" << EOF
# 📋 CONTEXT INDEX - $PROJECT_NAME

> **Domain**: $DOMAIN | **Team**: $TEAM | **Created**: $CURRENT_DATE

## 🎯 **PROJECT OVERVIEW**
Dự án **$PROJECT_NAME** trong domain **$DOMAIN** được tạo từ brain template system.

## 📂 **CONTEXT FILES**
- **SCOPE.md**: Project scope definition và goals
- **DOMAIN_MAP.md**: Domain entities và workflows  
- **tasks/ACTIVE_TASKS.json**: Current active tasks tracking

## 🚀 **QUICK START**
1. Review SCOPE.md để hiểu project goals
2. Check tasks/ACTIVE_TASKS.json cho current tasks
3. Update DOMAIN_MAP.md với domain-specific info

---
*Auto-generated by create-brain-from-template.sh*
*Created: $CURRENT_DATETIME*
EOF

success "Tạo context index: context/CONTEXT_INDEX.md"

# Tạo daily log
TODAY_LOG="$TARGET_PATH/logs/daily/$CURRENT_DATE.md"
cat > "$TODAY_LOG" << EOF
# 📅 Daily Log - $CURRENT_DATE

## 🚀 **PROJECT SETUP**
- **Time**: $CURRENT_DATETIME
- **Project**: $PROJECT_NAME
- **Domain**: $DOMAIN
- **Team**: $TEAM

## ✅ **COMPLETED**
- Brain system được setup từ template
- Template files được copy và customize  
- Placeholders được thay thế tự động

## 📝 **NEXT ACTIONS**
- Review SCOPE.md và update goals if needed
- Add specific tasks vào ACTIVE_TASKS.json
- Customize DOMAIN_MAP.md với domain entities

---
*Auto-generated by brain template system*
EOF

success "Tạo daily log: logs/daily/$CURRENT_DATE.md"

# Tính thời gian
END_TIME=$(date +%s)
DURATION=$((END_TIME - START_TIME))

info ""
info "🎉 HOÀN THÀNH SETUP BRAIN SYSTEM!"
info "⏱️ Thời gian setup: ${DURATION} giây"
info "📁 Files được tạo: $((${#COPIED_FILES[@]} + 2))"
info "🔄 Placeholders được thay: $REPLACED_COUNT files"

info ""
info "📋 **NEXT STEPS**:"
info "1. Review file SCOPE.md"
info "2. Update tasks/ACTIVE_TASKS.json với initial tasks"
info "3. Customize DOMAIN_MAP.md nếu cần"  
info "4. Chạy validate-brain-template.sh để check"

info ""
success "🧠 Brain system đã sẵn sàng cho dự án $PROJECT_NAME!"