# 🚀 CREATE BRAIN FROM TEMPLATE - PowerShell Script
# Mục tiêu: Setup brain system từ template trong < 5 phút

param(
    [Parameter(Mandatory = $true)]
    [string]$ProjectName,
    
    [Parameter(Mandatory = $false)]
    [string]$Team = "Development Team",
    
    [Parameter(Mandatory = $false)]
    [string]$Domain = "SaaS",
    
    [Parameter(Mandatory = $false)]
    [string]$TargetPath = ".brain"
)

# Màu sắc cho output
function Write-Success { param($msg) Write-Host "✅ $msg" -ForegroundColor Green }
function Write-Warning { param($msg) Write-Host "⚠️ $msg" -ForegroundColor Yellow }  
function Write-Error { param($msg) Write-Host "❌ $msg" -ForegroundColor Red }
function Write-Info { param($msg) Write-Host "ℹ️ $msg" -ForegroundColor Cyan }

Write-Info "🚀 BẮT ĐẦU SETUP BRAIN SYSTEM CHO DỰ ÁN: $ProjectName"
$startTime = Get-Date
Write-Info "⏱️ Thời gian bắt đầu: $startTime"

# Kiểm tra PROJECT_TEMPLATE tồn tại
$templatePath = ".brain/PROJECT_TEMPLATE"
if (-not (Test-Path $templatePath)) {
    Write-Error "Không tìm thấy thư mục $templatePath"
    Write-Info "Hãy đảm bảo bạn đang chạy script từ root directory của dự án"
    exit 1
}

Write-Success "Tìm thấy template directory: $templatePath"

# Tạo thư mục đích nếu chưa tồn tại
if (-not (Test-Path $TargetPath)) {
    New-Item -ItemType Directory -Path $TargetPath -Force | Out-Null
    Write-Success "Đã tạo thư mục: $TargetPath"
}

# Tạo thư mục con cần thiết
$subDirs = @("tasks", "context", "logs/daily")
foreach ($dir in $subDirs) {
    $fullPath = Join-Path $TargetPath $dir
    if (-not (Test-Path $fullPath)) {
        New-Item -ItemType Directory -Path $fullPath -Force | Out-Null
        Write-Success "Tạo thư mục: $fullPath"
    }
}

# Copy và rename template files
$templateFiles = @{
    "TEMPLATE_SCOPE.md"        = "SCOPE.md"
    "TEMPLATE_DOMAIN_MAP.md"   = "DOMAIN_MAP.md" 
    "SAMPLE_ACTIVE_TASKS.json" = "tasks/ACTIVE_TASKS.json"
    "QUICK_START.md"           = "QUICK_START.md"
    "SETUP_GUIDE.md"           = "SETUP_GUIDE.md"
    "INDEX.md"                 = "README.md"
}

Write-Info "📁 Đang copy và rename template files..."
$copiedFiles = @()

foreach ($sourceFile in $templateFiles.Keys) {
    $sourcePath = Join-Path $templatePath $sourceFile
    $destFile = $templateFiles[$sourceFile] 
    $destPath = Join-Path $TargetPath $destFile
    
    if (Test-Path $sourcePath) {
        Copy-Item $sourcePath $destPath -Force
        $copiedFiles += $destPath
        Write-Success "Copied: $sourceFile → $destFile"
    }
    else {
        Write-Warning "Không tìm thấy: $sourceFile"
    }
}

# Tạo danh sách placeholder cần thay thế
$currentDate = Get-Date -Format "yyyy-MM-dd"
$currentDateTime = Get-Date -Format "yyyy-MM-dd HH:mm"

$placeholders = @{
    "{{PROJECT_NAME}}"     = $ProjectName
    "{{TEAM_NAME}}"        = $Team
    "{{DOMAIN}}"           = $Domain
    "{{CURRENT_DATE}}"     = $currentDate
    "{{LAST_UPDATED}}"     = $currentDate
    "{{LAST_UPDATE_DATE}}" = $currentDateTime
    "{{VERSION}}"          = "1.0.0"
    "{{STATUS}}"           = "Development"
    "{{CREATION_DATE}}"    = $currentDate
}

Write-Info "🔄 Đang thay thế placeholders trong các file..."
$replacedCount = 0

foreach ($filePath in $copiedFiles) {
    if (Test-Path $filePath) {
        $content = Get-Content $filePath -Raw -Encoding UTF8
        $originalContent = $content
        
        foreach ($placeholder in $placeholders.Keys) {
            $replacement = $placeholders[$placeholder]
            $content = $content -replace [regex]::Escape($placeholder), $replacement
        }
        
        if ($content -ne $originalContent) {
            Set-Content $filePath $content -Encoding UTF8
            $replacedCount++
            Write-Success "Updated placeholders in: $(Split-Path $filePath -Leaf)"
        }
    }
}

# Tạo CONTEXT_INDEX.md
$contextIndexPath = Join-Path $TargetPath "context/CONTEXT_INDEX.md"
$contextContent = @"
# 📋 CONTEXT INDEX - $ProjectName

> **Domain**: $Domain | **Team**: $Team | **Created**: $currentDate

## 🎯 **PROJECT OVERVIEW**
Dự án **$ProjectName** trong domain **$Domain** được tạo từ brain template system.

## 📂 **CONTEXT FILES**
- **SCOPE.md**: Project scope definition và goals
- **DOMAIN_MAP.md**: Domain entities và workflows
- **tasks/ACTIVE_TASKS.json**: Current active tasks tracking

## 🚀 **QUICK START**
1. Review SCOPE.md để hiểu project goals
2. Check tasks/ACTIVE_TASKS.json cho current tasks
3. Update DOMAIN_MAP.md với domain-specific info

---
*Auto-generated by create-brain-from-template.ps1*
*Created: $currentDateTime*
"@

Set-Content $contextIndexPath $contextContent -Encoding UTF8
Write-Success "Tạo context index: context/CONTEXT_INDEX.md"

# Tạo daily log entry
$todayLog = Join-Path $TargetPath "logs/daily/$currentDate.md"
$logContent = @"
# 📅 Daily Log - $currentDate

## 🚀 **PROJECT SETUP**
- **Time**: $currentDateTime
- **Project**: $ProjectName
- **Domain**: $Domain
- **Team**: $Team

## ✅ **COMPLETED**
- Brain system được setup từ template
- Template files được copy và customize
- Placeholders được thay thế tự động

## 📝 **NEXT ACTIONS**
- Review SCOPE.md và update goals if needed
- Add specific tasks vào ACTIVE_TASKS.json
- Customize DOMAIN_MAP.md với domain entities

---
*Auto-generated by brain template system*
"@

Set-Content $todayLog $logContent -Encoding UTF8
Write-Success "Tạo daily log: logs/daily/$currentDate.md"

# Tính thời gian setup
$endTime = Get-Date
$duration = ($endTime - $startTime).TotalSeconds

Write-Info ""
Write-Info "🎉 HOÀN THÀNH SETUP BRAIN SYSTEM!"
Write-Info "⏱️ Thời gian setup: $([math]::Round($duration, 1)) giây"
Write-Info "📁 Files được tạo: $($copiedFiles.Count + 2)"  
Write-Info "🔄 Placeholders được thay: $replacedCount files"

Write-Info ""
Write-Info "📋 **NEXT STEPS**:"
Write-Info "1. Review file SCOPE.md"
Write-Info "2. Update tasks/ACTIVE_TASKS.json với initial tasks"
Write-Info "3. Customize DOMAIN_MAP.md nếu cần"
Write-Info "4. Chạy validate-brain-template.ps1 để check"

Write-Info ""
Write-Success "🧠 Brain system đã sẵn sàng cho dự án $ProjectName!"