# =====================================================
# LOGSTASH CONFIGURATION
# Airbnb WebApp - Vietnamese Log Processing
# =====================================================

# Node Settings
node.name: "logstash-airbnb-node"

# Path Settings
path.data: /usr/share/logstash/data
path.logs: /usr/share/logstash/logs
path.settings: /usr/share/logstash/config

# Pipeline Settings
pipeline.id: "airbnb-main-pipeline"
pipeline.workers: 2
pipeline.batch.size: 125
pipeline.batch.delay: 50

# Queue Settings
queue.type: memory
queue.max_events: 0
queue.max_bytes: 1gb

# Dead Letter Queue
dead_letter_queue.enable: false

# API Settings
api.enabled: true
api.http.host: 0.0.0.0
api.http.port: 9600

# Logging Settings
log.level: info
slowlog.threshold.warn: 2s
slowlog.threshold.info: 1s
slowlog.threshold.debug: 500ms

# Monitoring Settings
monitoring.enabled: false
monitoring.elasticsearch.hosts: ["http://elasticsearch:9200"]

# Config Settings
config.reload.automatic: true
config.reload.interval: 3s

# Locale Settings cho Vietnamese
config.support_escapes: true